[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 2

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4a8ad1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"